### ISSUE TITLE
don't sync the .storeit directory

### ISSUE THREAD

**Issue by Sevauk** [Sevauk/storeit#172]
since it is within the synced directory for now the chunks are synced. We should put this somewhere else

**Comment by kirly-af** [comment]
The `.storeit` is not synced since it is ignored by the watcher, see:
* [watcher](https://github.com/Sevauk/storeit/blob/master/desktop-app/src/daemon/watcher.js#L63)
* [client](https://github.com/Sevauk/storeit/blob/master/desktop-app/src/daemon/client.js#L23)
