### ISSUE TITLE
graphic oauth

### ISSUE THREAD

**Issue by kirly-af** [Sevauk/storeit#66]

**Comment by kirly-af** [comment]
@Sevauk: alternatively, we could do [this](http://stackoverflow.com/a/13381847)

**Comment by Sirttas** [comment]
The branche "desktop/#66-feat" got merged from "desktop/#65-feat" please check that everything is ok before merging it.

**Comment by kirly-af** [comment]
LGTM. Though I have no time to test it right now. Is it functional ?
Also, remind the fact changes are expected on oauth implementation on `desktop/#65-feat`.

**Comment by Sirttas** [comment]
It is functional. We just need to wait desktop/#65-feat do be completed first.
