### ISSUE TITLE
make a basic working server

### ISSUE THREAD

**Issue by Sevauk** [Sevauk/storeit#7]

**Comment by kirly-af** [comment]
Tools we should use:
- nodemon during dev
- mocha + chai + coffeescript for unit testing
- babel-runtime with those presets: es2015 and stage3
- eslint to impose a common coding-style and ensure good practices
- editorconfig (do I have to say why :p )
- ternjs for intellisense
- write a vagrant box ?

**Comment by Sevauk** [comment]
Docker ? Maybe ?
